# Generated by Django 2.1.5 on 2019-02-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0004_auto_20190123_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_billinformation_destination', to='records.CallRecord')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_billinformation_source', to='records.CallRecord')),
            ],
        ),
    ]
