# Generated by Django 2.1.5 on 2019-02-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinformation',
            name='destination',
        ),
    ]
