# Generated by Django 2.1.5 on 2019-01-23 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20190122_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='destination',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='The phone number format is AAXXXXXXXXX, where AA is the area code and XXXXXXXXX is the phone number. The area code is always composed of two digits while the phone number can be composed of 8 or 9 digits.', regex='^\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='The phone number format is AAXXXXXXXXX, where AA is the area code and XXXXXXXXX is the phone number. The area code is always composed of two digits while the phone number can be composed of 8 or 9 digits.', regex='^\\d{10,11}$')]),
        ),
    ]
